[build]
  command = "git submodule update --init --recursive && git submodule foreach git pull origin master && npm run publish:blog && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
